import { Contractor, MaintenanceRecord, RoadIssue, RoadSegment, SystemAlert } from '../types';

export const SEED_CONTRACTORS: Contractor[] = [
  {
    id: 'C-101',
    name: 'Rajesh Kulkarni',
    company: 'BMC Central Highway Works Ltd',
    email: 'rajesh.k@bmcroads.gov.in',
    phone: '+91 98201 44521',
    assignedZones: ['Zone 1 - South Mumbai', 'Zone 2 - Central Mumbai'],
    activeIssuesCount: 3,
    completedIssuesCount: 48,
    averageResolutionDays: 2.4,
    rating: 4.8,
    status: 'ACTIVE',
  },
  {
    id: 'C-102',
    name: 'Priya Sharma',
    company: 'Western Suburban Pavement Engineers',
    email: 'priya.sharma@suburbaninfra.in',
    phone: '+91 98210 88203',
    assignedZones: ['Zone 3 - Western Suburbs'],
    activeIssuesCount: 4,
    completedIssuesCount: 39,
    averageResolutionDays: 3.1,
    rating: 4.5,
    status: 'ACTIVE',
  },
  {
    id: 'C-103',
    name: 'Amit Deshmukh',
    company: 'Eastern Express Infrastructure Corp',
    email: 'amit.d@easterninfra.in',
    phone: '+91 98199 12345',
    assignedZones: ['Zone 4 - Eastern Suburbs'],
    activeIssuesCount: 5,
    completedIssuesCount: 52,
    averageResolutionDays: 2.8,
    rating: 4.6,
    status: 'ACTIVE',
  },
  {
    id: 'C-104',
    name: 'Sunil Patil',
    company: 'Apex Urban Bituminous Services',
    email: 'sunil.p@apexroads.in',
    phone: '+91 98334 77651',
    assignedZones: ['Zone 5 - North Mumbai', 'Zone 3 - Western Suburbs'],
    activeIssuesCount: 2,
    completedIssuesCount: 31,
    averageResolutionDays: 3.5,
    rating: 4.2,
    status: 'ACTIVE',
  },
];

export const SEED_ROADS: RoadSegment[] = [
  {
    id: 'MH-MUM-001',
    name: 'Marine Drive Promenade Segment A',
    ward: 'A Ward',
    zone: 'Zone 1 - South Mumbai',
    lengthKm: 1.8,
    surfaceType: 'Bituminous Mix',
    lanes: 6,
    condition: 'GOOD',
    healthScore: 87,
    locationDescription: 'Netaji Subhash Chandra Bose Road, Nariman Point to Air India Bldg',
    coordinates: {
      lat: 18.9256,
      lng: 72.8242,
      startPoint: 'NCPA Junction',
      endPoint: 'Air India Headquarters',
    },
    contractorId: 'C-101',
    contractorName: 'BMC Central Highway Works Ltd',
    lastMaintenanceDate: '2026-08-15',
    nextScheduledMaintenance: '2027-02-15',
    openIssuesCount: 0,
    resolvedIssuesCount: 14,
    iotStatus: {
      deviceId: 'IOT-MUM-001-A',
      status: 'NORMAL',
      water_cm: 0.2,
      vibration_g: 0.08,
      lux: 620,
      isOnline: true,
      lastUpdate: '2026-10-06T23:30:00Z',
      anomalyDetected: false,
    },
    qrStatus: 'ACTIVE',
    qrGeneratedDate: '2026-01-10',
    recurringDefectCount: 0,
    lastRepairDaysAgo: 52,
    averageDaysBetweenRepairs: 180,
  },
  {
    id: 'MH-MUM-002',
    name: 'LBS Marg Kurla Junction',
    ward: 'L Ward',
    zone: 'Zone 2 - Central Mumbai',
    lengthKm: 2.4,
    surfaceType: 'Asphalt',
    lanes: 4,
    condition: 'CRITICAL',
    healthScore: 34,
    locationDescription: 'Lal Bahadur Shastri Marg, Kurla West near Kamani Junction',
    coordinates: {
      lat: 19.0688,
      lng: 72.8834,
      startPoint: 'Sheetal Cinema Junction',
      endPoint: 'Kamani Tubes Flyover Entry',
    },
    contractorId: 'C-101',
    contractorName: 'BMC Central Highway Works Ltd',
    lastMaintenanceDate: '2026-09-14',
    nextScheduledMaintenance: '2026-10-01', // overdue
    openIssuesCount: 4,
    resolvedIssuesCount: 29,
    iotStatus: {
      deviceId: 'IOT-MUM-002-K',
      status: 'WATERLOGGING',
      water_cm: 8.5,
      vibration_g: 0.65,
      lux: 310,
      isOnline: true,
      lastUpdate: '2026-10-06T23:45:00Z',
      anomalyDetected: true,
      alertMessage: 'Standing water >8cm detected near median stormwater culvert',
    },
    qrStatus: 'ACTIVE',
    qrGeneratedDate: '2026-01-12',
    recurringDefectCount: 5,
    lastRepairDaysAgo: 22,
    averageDaysBetweenRepairs: 28,
    isPriorityFlagged: true,
  },
  {
    id: 'MH-MUM-003',
    name: 'SV Road Andheri Subway Underpass',
    ward: 'K-West Ward',
    zone: 'Zone 3 - Western Suburbs',
    lengthKm: 0.9,
    surfaceType: 'Concrete',
    lanes: 4,
    condition: 'POOR',
    healthScore: 48,
    locationDescription: 'Swami Vivekanand Road underpass connecting Andheri East & West',
    coordinates: {
      lat: 19.1197,
      lng: 72.8468,
      startPoint: 'Gokhale Bridge East Approach',
      endPoint: 'SV Road Junction West',
    },
    contractorId: 'C-102',
    contractorName: 'Western Suburban Pavement Engineers',
    lastMaintenanceDate: '2026-07-20',
    nextScheduledMaintenance: '2026-10-20',
    openIssuesCount: 2,
    resolvedIssuesCount: 21,
    iotStatus: {
      deviceId: 'IOT-MUM-003-U',
      status: 'WARNING',
      water_cm: 4.8,
      vibration_g: 0.32,
      lux: 180,
      isOnline: true,
      lastUpdate: '2026-10-06T23:40:00Z',
      anomalyDetected: true,
      alertMessage: 'Elevated water accumulation rate during peak drainage cycle',
    },
    qrStatus: 'ACTIVE',
    qrGeneratedDate: '2026-02-01',
    recurringDefectCount: 3,
    lastRepairDaysAgo: 78,
    averageDaysBetweenRepairs: 45,
    isPriorityFlagged: true,
  },
  {
    id: 'MH-MUM-004',
    name: 'Eastern Express Highway Ghatkopar Flyover Base',
    ward: 'N Ward',
    zone: 'Zone 4 - Eastern Suburbs',
    lengthKm: 3.2,
    surfaceType: 'Bituminous Mix',
    lanes: 8,
    condition: 'WARNING',
    healthScore: 68,
    locationDescription: 'EEH Southbound carriageway between Ghatkopar Link Rd and Chedda Nagar',
    coordinates: {
      lat: 19.0856,
      lng: 72.9082,
      startPoint: 'Ghatkopar Bus Depot Exit',
      endPoint: 'Chedda Nagar Junction',
    },
    contractorId: 'C-103',
    contractorName: 'Eastern Express Infrastructure Corp',
    lastMaintenanceDate: '2026-06-10',
    nextScheduledMaintenance: '2026-12-10',
    openIssuesCount: 1,
    resolvedIssuesCount: 18,
    iotStatus: {
      deviceId: 'IOT-MUM-004-E',
      status: 'NORMAL',
      water_cm: 0.0,
      vibration_g: 0.22,
      lux: 540,
      isOnline: true,
      lastUpdate: '2026-10-06T23:25:00Z',
      anomalyDetected: false,
    },
    qrStatus: 'ACTIVE',
    qrGeneratedDate: '2026-01-15',
    recurringDefectCount: 1,
    lastRepairDaysAgo: 118,
    averageDaysBetweenRepairs: 110,
  },
  {
    id: 'MH-MUM-005',
    name: 'Linking Road Bandra West Sector 3',
    ward: 'H-West Ward',
    zone: 'Zone 3 - Western Suburbs',
    lengthKm: 1.5,
    surfaceType: 'Asphalt',
    lanes: 4,
    condition: 'GOOD',
    healthScore: 82,
    locationDescription: 'Between Bandra Talkies and Khar Telephone Exchange',
    coordinates: {
      lat: 19.0596,
      lng: 72.8354,
      startPoint: 'Waterfield Road Junction',
      endPoint: 'Khar Danda Road Cross',
    },
    contractorId: 'C-102',
    contractorName: 'Western Suburban Pavement Engineers',
    lastMaintenanceDate: '2026-08-05',
    nextScheduledMaintenance: '2027-02-05',
    openIssuesCount: 0,
    resolvedIssuesCount: 16,
    iotStatus: {
      deviceId: 'IOT-MUM-005-B',
      status: 'NORMAL',
      water_cm: 0.1,
      vibration_g: 0.11,
      lux: 590,
      isOnline: true,
      lastUpdate: '2026-10-06T23:15:00Z',
      anomalyDetected: false,
    },
    qrStatus: 'ACTIVE',
    qrGeneratedDate: '2026-02-05',
    recurringDefectCount: 0,
    lastRepairDaysAgo: 62,
    averageDaysBetweenRepairs: 140,
  },
  {
    id: 'MH-MUM-006',
    name: 'Western Express Highway Goregaon East Hub',
    ward: 'P-South Ward',
    zone: 'Zone 3 - Western Suburbs',
    lengthKm: 2.8,
    surfaceType: 'Bituminous Mix',
    lanes: 8,
    condition: 'WARNING',
    healthScore: 74,
    locationDescription: 'WEH Northbound stretch opposite Hub Mall to Aarey Flyover',
    coordinates: {
      lat: 19.1553,
      lng: 72.8574,
      startPoint: 'Aarey Milk Colony Turn',
      endPoint: 'Oberoi Mall Flyover Start',
    },
    contractorId: 'C-104',
    contractorName: 'Apex Urban Bituminous Services',
    lastMaintenanceDate: '2026-05-30',
    nextScheduledMaintenance: '2026-11-30',
    openIssuesCount: 1,
    resolvedIssuesCount: 22,
    iotStatus: {
      deviceId: 'IOT-MUM-006-G',
      status: 'NORMAL',
      water_cm: 0.0,
      vibration_g: 0.28,
      lux: 480,
      isOnline: true,
      lastUpdate: '2026-10-06T23:35:00Z',
      anomalyDetected: false,
    },
    qrStatus: 'ACTIVE',
    qrGeneratedDate: '2026-01-20',
    recurringDefectCount: 1,
    lastRepairDaysAgo: 129,
    averageDaysBetweenRepairs: 120,
  },
  {
    id: 'MH-MUM-007',
    name: 'Senapati Bapat Marg Lower Parel Commercial Strip',
    ward: 'G-South Ward',
    zone: 'Zone 1 - South Mumbai',
    lengthKm: 2.1,
    surfaceType: 'Paver Block',
    lanes: 4,
    condition: 'POOR',
    healthScore: 52,
    locationDescription: 'Below Lower Parel Monorail Line from Phoenix Mills to One International Centre',
    coordinates: {
      lat: 19.0024,
      lng: 72.8296,
      startPoint: 'Delisle Road Flyover',
      endPoint: 'Currey Road Station West',
    },
    contractorId: 'C-101',
    contractorName: 'BMC Central Highway Works Ltd',
    lastMaintenanceDate: '2026-06-15',
    nextScheduledMaintenance: '2026-10-15',
    openIssuesCount: 2,
    resolvedIssuesCount: 25,
    iotStatus: {
      deviceId: 'IOT-MUM-007-L',
      status: 'WARNING',
      water_cm: 1.2,
      vibration_g: 0.48,
      lux: 390,
      isOnline: true,
      lastUpdate: '2026-10-06T23:20:00Z',
      anomalyDetected: true,
      alertMessage: 'Repeated high vibration signatures from uneven settlement beneath paver blocks',
    },
    qrStatus: 'REPLACEMENT_REQUIRED',
    qrGeneratedDate: '2025-11-20',
    recurringDefectCount: 4,
    lastRepairDaysAgo: 113,
    averageDaysBetweenRepairs: 42,
  },
  {
    id: 'MH-MUM-008',
    name: 'Sion-Dharavi Link Road Corridor',
    ward: 'G-North Ward',
    zone: 'Zone 2 - Central Mumbai',
    lengthKm: 1.6,
    surfaceType: 'Asphalt',
    lanes: 4,
    condition: 'CRITICAL',
    healthScore: 38,
    locationDescription: 'Connecting 90 Feet Road Dharavi to Sion Railway Station South Gate',
    coordinates: {
      lat: 19.0432,
      lng: 72.8615,
      startPoint: 'Kala Killa Junction',
      endPoint: 'Sion Circle Approach',
    },
    contractorId: 'C-101',
    contractorName: 'BMC Central Highway Works Ltd',
    lastMaintenanceDate: '2026-07-02',
    nextScheduledMaintenance: '2026-09-30', // overdue
    openIssuesCount: 3,
    resolvedIssuesCount: 34,
    iotStatus: {
      deviceId: 'IOT-MUM-008-S',
      status: 'FAULT',
      water_cm: 3.5,
      vibration_g: 0.15,
      lux: 110,
      isOnline: false,
      lastUpdate: '2026-10-06T18:00:00Z',
      anomalyDetected: true,
      alertMessage: 'Sensor node telemetry packet timeout (>5 hours offline)',
    },
    qrStatus: 'ACTIVE',
    qrGeneratedDate: '2026-01-08',
    recurringDefectCount: 4,
    lastRepairDaysAgo: 96,
    averageDaysBetweenRepairs: 35,
    isPriorityFlagged: true,
  },
  {
    id: 'MH-MUM-009',
    name: 'Central Avenue Hiranandani Gardens Powai',
    ward: 'S Ward',
    zone: 'Zone 4 - Eastern Suburbs',
    lengthKm: 1.9,
    surfaceType: 'Concrete',
    lanes: 4,
    condition: 'GOOD',
    healthScore: 94,
    locationDescription: 'Main dual-carriageway loop around Galleria and Heritage Garden',
    coordinates: {
      lat: 19.1176,
      lng: 72.9064,
      startPoint: 'JVLR Powai Entry',
      endPoint: 'Forest Park Boulevard',
    },
    contractorId: 'C-103',
    contractorName: 'Eastern Express Infrastructure Corp',
    lastMaintenanceDate: '2026-09-01',
    nextScheduledMaintenance: '2027-03-01',
    openIssuesCount: 0,
    resolvedIssuesCount: 8,
    iotStatus: {
      deviceId: 'IOT-MUM-009-P',
      status: 'NORMAL',
      water_cm: 0.0,
      vibration_g: 0.05,
      lux: 650,
      isOnline: true,
      lastUpdate: '2026-10-06T23:42:00Z',
      anomalyDetected: false,
    },
    qrStatus: 'ACTIVE',
    qrGeneratedDate: '2026-03-01',
    recurringDefectCount: 0,
    lastRepairDaysAgo: 35,
    averageDaysBetweenRepairs: 240,
  },
  {
    id: 'MH-MUM-010',
    name: 'BKC Avenue G-Block Bandra Kurla Complex',
    ward: 'H-East Ward',
    zone: 'Zone 2 - Central Mumbai',
    lengthKm: 2.0,
    surfaceType: 'Concrete',
    lanes: 6,
    condition: 'GOOD',
    healthScore: 91,
    locationDescription: 'BKC Boulevard fronting MMRDA Grounds, US Consulate, and Jio Convention Centre',
    coordinates: {
      lat: 19.0662,
      lng: 72.8687,
      startPoint: 'Bharat Diamond Bourse Gate',
      endPoint: 'Kalanagar Flyover Connector',
    },
    contractorId: 'C-103',
    contractorName: 'Eastern Express Infrastructure Corp',
    lastMaintenanceDate: '2026-08-28',
    nextScheduledMaintenance: '2027-02-28',
    openIssuesCount: 0,
    resolvedIssuesCount: 11,
    iotStatus: {
      deviceId: 'IOT-MUM-010-B',
      status: 'NORMAL',
      water_cm: 0.0,
      vibration_g: 0.06,
      lux: 610,
      isOnline: true,
      lastUpdate: '2026-10-06T23:38:00Z',
      anomalyDetected: false,
    },
    qrStatus: 'ACTIVE',
    qrGeneratedDate: '2026-01-05',
    recurringDefectCount: 0,
    lastRepairDaysAgo: 39,
    averageDaysBetweenRepairs: 210,
  },
];

export const SEED_ISSUES: RoadIssue[] = [
  {
    id: 'ISSUE-2026-000841',
    roadId: 'MH-MUM-002',
    roadName: 'LBS Marg Kurla Junction',
    locationDetails: 'Near Kamani bus stop, 30m before traffic light heading towards Sion',
    gpsCoordinates: {
      lat: 19.0689,
      lng: 72.8835,
      verified: true,
    },
    reportedAt: '2026-10-05T08:30:00Z',
    reporterName: 'Sunil G.',
    reporterContact: '+91 98200 99881',
    isPublicAnonymous: false,
    isSafetyHazard: true,
    hazardConfirmed: true,
    problemType: 'pothole',
    severity: 'CRITICAL',
    description: 'Deep cluster of potholes right in the middle lane causing two-wheelers to skid and swerve violently.',
    status: 'REPORTED',
    photoUrl: 'https://images.unsplash.com/photo-1515162816999-a0c47dc192f7?auto=format&fit=crop&w=800&q=80',
    aiAnalysis: {
      problemType: 'pothole',
      confidence: 96,
      severity: 'CRITICAL',
      affectedArea: 'Approx 1.8m x 1.4m, depth ~14cm',
      recommendedAction: 'Immediate barricading, cold mix asphalt temporary plug followed by hot mix base compaction within 24 hours.',
      note: 'High severity pothole with exposed aggregate base. Immediate vehicle suspension and tire damage risk.',
      isSimulated: true,
      analyzedAt: '2026-10-05T08:31:12Z',
      modelUsed: 'gemini-3.8-flash (Simulated fallback)',
    },
    auditTrail: [
      {
        id: 'aud-001',
        timestamp: '2026-10-05T08:30:00Z',
        user: 'Citizen Sunil G.',
        role: 'CITIZEN',
        action: 'Report Submitted',
        comment: 'Report created via QR scan at Kurla site.',
      },
      {
        id: 'aud-002',
        timestamp: '2026-10-05T08:31:12Z',
        user: 'Municipal AI Engine',
        role: 'SUPER_ADMIN',
        action: 'AI Defect Assessment Attached',
        comment: 'Automated classification: Pothole (96% confidence, CRITICAL severity).',
      },
    ],
  },
  {
    id: 'ISSUE-2026-000792',
    roadId: 'MH-MUM-002',
    roadName: 'LBS Marg Kurla Junction',
    locationDetails: 'Stormwater median drain overflow section',
    gpsCoordinates: {
      lat: 19.0686,
      lng: 72.8831,
      verified: true,
    },
    reportedAt: '2026-10-03T14:15:00Z',
    isPublicAnonymous: true,
    isSafetyHazard: true,
    hazardConfirmed: true,
    problemType: 'waterlogging',
    severity: 'HIGH',
    description: 'Persistent 8cm water accumulation covering outer 2 lanes even without heavy rain.',
    status: 'IN_PROGRESS',
    photoUrl: 'https://images.unsplash.com/photo-1541888946425-d0fbb1861593?auto=format&fit=crop&w=800&q=80',
    aiAnalysis: {
      problemType: 'waterlogging',
      confidence: 93,
      severity: 'HIGH',
      affectedArea: 'Approx 15m stretch along curb, standing depth 8-10cm',
      recommendedAction: 'Desilting culvert intake grate and jet cleaning lateral drain pipes.',
      note: 'Compromised pavement subgrade due to constant saturation. Premature stripping likely.',
      isSimulated: true,
      analyzedAt: '2026-10-03T14:16:05Z',
      modelUsed: 'gemini-3.8-flash',
    },
    assignedContractorId: 'C-101',
    assignedContractorName: 'BMC Central Highway Works Ltd',
    auditTrail: [
      {
        id: 'aud-003',
        timestamp: '2026-10-03T14:15:00Z',
        user: 'Citizen Anonymous',
        role: 'CITIZEN',
        action: 'Report Submitted',
      },
      {
        id: 'aud-004',
        timestamp: '2026-10-03T16:00:00Z',
        user: 'Inspector D. Shinde',
        role: 'INSPECTOR',
        action: 'Verified On Site',
        comment: 'Confirmed water depth 8.5cm; drainage blockage verified.',
      },
      {
        id: 'aud-005',
        timestamp: '2026-10-04T09:00:00Z',
        user: 'Admin BMC Roads',
        role: 'ADMIN',
        action: 'Assigned to Contractor',
        comment: 'Assigned to C-101 for emergency suction pumping and desilting.',
      },
      {
        id: 'aud-006',
        timestamp: '2026-10-04T13:30:00Z',
        user: 'Rajesh Kulkarni',
        role: 'CONTRACTOR',
        action: 'Status Changed to IN_PROGRESS',
        comment: 'Suction tanker deployed at Kurla junction.',
      },
    ],
  },
  {
    id: 'ISSUE-2026-000910',
    roadId: 'MH-MUM-003',
    roadName: 'SV Road Andheri Subway Underpass',
    locationDetails: 'Underpass drainage grate damaged, iron grating dislodged',
    reportedAt: '2026-10-04T11:00:00Z',
    isPublicAnonymous: true,
    isSafetyHazard: true,
    hazardConfirmed: true,
    problemType: 'damaged_drainage',
    severity: 'HIGH',
    description: 'Heavy vehicle tire dislodged the steel storm drain grating leaving a dangerous trench.',
    status: 'IN_PROGRESS',
    photoUrl: 'https://images.unsplash.com/photo-1584467735871-8e85353a8413?auto=format&fit=crop&w=800&q=80',
    aiAnalysis: {
      problemType: 'damaged_drainage',
      confidence: 91,
      severity: 'HIGH',
      affectedArea: 'Length 2.4m, width 0.6m open trench gap',
      recommendedAction: 'Fabrication of heavy-gauge interlocking cast iron grate with tamper locks.',
      note: 'Immediate hazard to two-wheelers and pedestrians; traffic barricades required.',
      isSimulated: true,
      analyzedAt: '2026-10-04T11:01:20Z',
      modelUsed: 'gemini-3.8-flash',
    },
    assignedContractorId: 'C-102',
    assignedContractorName: 'Western Suburban Pavement Engineers',
    auditTrail: [
      {
        id: 'aud-007',
        timestamp: '2026-10-04T11:00:00Z',
        user: 'Citizen',
        role: 'CITIZEN',
        action: 'Report Submitted',
      },
      {
        id: 'aud-008',
        timestamp: '2026-10-04T11:45:00Z',
        user: 'Admin',
        role: 'ADMIN',
        action: 'Assigned to Contractor',
        comment: 'Dispatched emergency barricading team.',
      },
    ],
  },
  {
    id: 'ISSUE-2026-000955',
    roadId: 'MH-MUM-007',
    roadName: 'Senapati Bapat Marg Lower Parel Commercial Strip',
    locationDetails: 'Pillar #42 Monorail base, left lane settlement',
    reportedAt: '2026-10-05T16:20:00Z',
    isPublicAnonymous: false,
    reporterName: 'Kavita M.',
    isSafetyHazard: false,
    hazardConfirmed: false,
    problemType: 'surface_damage',
    severity: 'MEDIUM',
    description: 'Uneven paver blocks have sunken by roughly 5 inches, causing cars to scrape their undercarriages.',
    status: 'ASSIGNED',
    photoUrl: 'https://images.unsplash.com/photo-1578873375972-0498bce1ff03?auto=format&fit=crop&w=800&q=80',
    aiAnalysis: {
      problemType: 'surface_damage',
      confidence: 89,
      severity: 'MEDIUM',
      affectedArea: '3.5m x 2.2m sunken paver bed',
      recommendedAction: 'Excavate loose sand bedding, compact wet gravel substrate, and reinstall interlocking blocks.',
      note: 'Localized subgrade settlement. Low immediate catastrophe risk, moderate vehicle disruption.',
      isSimulated: true,
      analyzedAt: '2026-10-05T16:21:40Z',
      modelUsed: 'gemini-3.8-flash',
    },
    assignedContractorId: 'C-101',
    assignedContractorName: 'BMC Central Highway Works Ltd',
    auditTrail: [
      {
        id: 'aud-009',
        timestamp: '2026-10-05T16:20:00Z',
        user: 'Kavita M.',
        role: 'CITIZEN',
        action: 'Report Submitted',
      },
      {
        id: 'aud-010',
        timestamp: '2026-10-06T10:00:00Z',
        user: 'Inspector D. Shinde',
        role: 'INSPECTOR',
        action: 'Verified',
        comment: 'Subgrade subsidence noted.',
      },
    ],
  },
  {
    id: 'ISSUE-2026-000880',
    roadId: 'MH-MUM-008',
    roadName: 'Sion-Dharavi Link Road Corridor',
    locationDetails: 'Opposite 90 Feet Road corner near public dispensary',
    reportedAt: '2026-10-04T09:10:00Z',
    isPublicAnonymous: true,
    isSafetyHazard: true,
    hazardConfirmed: true,
    problemType: 'pothole',
    severity: 'CRITICAL',
    description: 'Huge pothole crater across two lanes. Auto-rickshaws overturning risk.',
    status: 'VERIFIED',
    photoUrl: 'https://images.unsplash.com/photo-1515162816999-a0c47dc192f7?auto=format&fit=crop&w=800&q=80',
    aiAnalysis: {
      problemType: 'pothole',
      confidence: 95,
      severity: 'CRITICAL',
      affectedArea: 'Approx 2.2m x 1.6m, depth ~16cm',
      recommendedAction: 'Full depth patch: saw cut edges, tack coat, dense asphalt concrete layer.',
      note: 'Critical severity crater with water intrusion. High risk of accidents.',
      isSimulated: true,
      analyzedAt: '2026-10-04T09:12:00Z',
      modelUsed: 'gemini-3.8-flash',
    },
    auditTrail: [
      {
        id: 'aud-011',
        timestamp: '2026-10-04T09:10:00Z',
        user: 'Citizen',
        role: 'CITIZEN',
        action: 'Report Submitted',
      },
      {
        id: 'aud-012',
        timestamp: '2026-10-04T12:00:00Z',
        user: 'Inspector R. Vernekar',
        role: 'INSPECTOR',
        action: 'Verified',
        comment: 'Confirmed critical hazard status.',
      },
    ],
  },
];

export const SEED_MAINTENANCE: MaintenanceRecord[] = [
  {
    id: 'MAINT-2026-0041',
    roadId: 'MH-MUM-001',
    roadName: 'Marine Drive Promenade Segment A',
    date: '2026-08-15',
    type: 'Pothole Patching',
    contractorId: 'C-101',
    contractorName: 'BMC Central Highway Works Ltd',
    costInr: 45000,
    description: 'Monsoon pre-seal and surface leveling of outer lane joint near NCPA turn.',
    status: 'COMPLETED',
    beforePhotoUrl: 'https://images.unsplash.com/photo-1515162816999-a0c47dc192f7?auto=format&fit=crop&w=800&q=80',
    afterPhotoUrl: 'https://images.unsplash.com/photo-1545459720-aac8509eb02c?auto=format&fit=crop&w=800&q=80',
    healthScoreBefore: 78,
    healthScoreAfter: 87,
    warrantyPeriodMonths: 12,
  },
  {
    id: 'MAINT-2026-0038',
    roadId: 'MH-MUM-002',
    roadName: 'LBS Marg Kurla Junction',
    date: '2026-09-14',
    type: 'Emergency Remediation',
    contractorId: 'C-101',
    contractorName: 'BMC Central Highway Works Ltd',
    costInr: 68000,
    description: 'Emergency cold mix asphalt filling of 3 major potholes after continuous monsoon downpours.',
    status: 'COMPLETED',
    beforePhotoUrl: 'https://images.unsplash.com/photo-1515162816999-a0c47dc192f7?auto=format&fit=crop&w=800&q=80',
    afterPhotoUrl: 'https://images.unsplash.com/photo-1545459720-aac8509eb02c?auto=format&fit=crop&w=800&q=80',
    healthScoreBefore: 28,
    healthScoreAfter: 42,
    warrantyPeriodMonths: 3,
  },
  {
    id: 'MAINT-2026-0035',
    roadId: 'MH-MUM-005',
    roadName: 'Linking Road Bandra West Sector 3',
    date: '2026-08-05',
    type: 'Cracks Sealing',
    contractorId: 'C-102',
    contractorName: 'Western Suburban Pavement Engineers',
    costInr: 85000,
    description: 'Hot-pour rubberized bitumen crack sealing along pedestrian crossing zone.',
    status: 'COMPLETED',
    beforePhotoUrl: 'https://images.unsplash.com/photo-1578873375972-0498bce1ff03?auto=format&fit=crop&w=800&q=80',
    afterPhotoUrl: 'https://images.unsplash.com/photo-1545459720-aac8509eb02c?auto=format&fit=crop&w=800&q=80',
    healthScoreBefore: 74,
    healthScoreAfter: 82,
    warrantyPeriodMonths: 18,
  },
];

export const SEED_ALERTS: SystemAlert[] = [
  {
    id: 'ALERT-001',
    type: 'HIGH_WATER',
    title: 'Waterlogging Alert: LBS Marg Kurla',
    message: 'Sensor IOT-MUM-002-K recorded water level at 8.5 cm (threshold >5.0 cm). Active flood risk.',
    roadId: 'MH-MUM-002',
    severity: 'CRITICAL',
    timestamp: '2026-10-06T23:45:00Z',
    acknowledged: false,
  },
  {
    id: 'ALERT-002',
    type: 'LOW_HEALTH',
    title: 'Critical Health Score (34): LBS Marg Kurla',
    message: 'Segment health dropped to 34/100 due to recurring potholes and water retention.',
    roadId: 'MH-MUM-002',
    severity: 'CRITICAL',
    timestamp: '2026-10-05T09:00:00Z',
    acknowledged: false,
  },
  {
    id: 'ALERT-003',
    type: 'LOW_HEALTH',
    title: 'Critical Health Score (38): Sion-Dharavi Link Road',
    message: 'Segment health at 38/100 with multiple high severity potholes reported.',
    roadId: 'MH-MUM-008',
    severity: 'CRITICAL',
    timestamp: '2026-10-04T10:00:00Z',
    acknowledged: false,
  },
  {
    id: 'ALERT-004',
    type: 'SENSOR_OFFLINE',
    title: 'Sensor Node Offline: MH-MUM-008',
    message: 'Node IOT-MUM-008-S has ceased sending telemetry packets for >5 hours.',
    roadId: 'MH-MUM-008',
    severity: 'WARNING',
    timestamp: '2026-10-06T18:00:00Z',
    acknowledged: false,
  },
  {
    id: 'ALERT-005',
    type: 'RECURRING_ISSUE',
    title: 'Recurring Maintenance Failure Flag',
    message: 'Segment MH-MUM-002 has failed 5 times in 140 days (avg 28 days between patches).',
    roadId: 'MH-MUM-002',
    severity: 'CRITICAL',
    timestamp: '2026-10-05T12:00:00Z',
    acknowledged: false,
  },
];
